//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentComplexServiceLibraryV1.Bank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Komitent", Namespace="www.soa.com/projekt/komitent/V4")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.FizicnaOseba))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.PoslovnaOseba))]
    public partial class Komitent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FizicnaOseba", Namespace="www.soa.com/projekt/fizicnaOseba/V4")]
    [System.SerializableAttribute()]
    public partial class FizicnaOseba : ApartmentComplexServiceLibraryV1.Bank.Komitent {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumRojstvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeInPriimekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaslovField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRojstva {
            get {
                return this.DatumRojstvaField;
            }
            set {
                if ((this.DatumRojstvaField.Equals(value) != true)) {
                    this.DatumRojstvaField = value;
                    this.RaisePropertyChanged("DatumRojstva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImeInPriimek {
            get {
                return this.ImeInPriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeInPriimekField, value) != true)) {
                    this.ImeInPriimekField = value;
                    this.RaisePropertyChanged("ImeInPriimek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PoslovnaOseba", Namespace="www.soa.com/projekt/poslovnaOseba/V4")]
    [System.SerializableAttribute()]
    public partial class PoslovnaOseba : ApartmentComplexServiceLibraryV1.Bank.Komitent {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DavcnaStevilkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivPodjetjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SedezPodjetjaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DavcnaStevilka {
            get {
                return this.DavcnaStevilkaField;
            }
            set {
                if ((object.ReferenceEquals(this.DavcnaStevilkaField, value) != true)) {
                    this.DavcnaStevilkaField = value;
                    this.RaisePropertyChanged("DavcnaStevilka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivPodjetja {
            get {
                return this.NazivPodjetjaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivPodjetjaField, value) != true)) {
                    this.NazivPodjetjaField = value;
                    this.RaisePropertyChanged("NazivPodjetja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SedezPodjetja {
            get {
                return this.SedezPodjetjaField;
            }
            set {
                if ((object.ReferenceEquals(this.SedezPodjetjaField, value) != true)) {
                    this.SedezPodjetjaField = value;
                    this.RaisePropertyChanged("SedezPodjetja");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UstvarjenRacunResponse", Namespace="www.soa.com/projekt/ustvarjenRacunResponse/V4")]
    [System.SerializableAttribute()]
    public partial class UstvarjenRacunResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stevilkaTRRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stevilkaTRR {
            get {
                return this.stevilkaTRRField;
            }
            set {
                if ((object.ReferenceEquals(this.stevilkaTRRField, value) != true)) {
                    this.stevilkaTRRField = value;
                    this.RaisePropertyChanged("stevilkaTRR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transakcija", Namespace="www.soa.com/projekt/transakcija/V4")]
    [System.SerializableAttribute()]
    public partial class Transakcija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Racun RacunIzdajateljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Racun RacunPrejemnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.TipTransakcije TipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZnesekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namen {
            get {
                return this.NamenField;
            }
            set {
                if ((object.ReferenceEquals(this.NamenField, value) != true)) {
                    this.NamenField = value;
                    this.RaisePropertyChanged("Namen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Racun RacunIzdajatelj {
            get {
                return this.RacunIzdajateljField;
            }
            set {
                if ((object.ReferenceEquals(this.RacunIzdajateljField, value) != true)) {
                    this.RacunIzdajateljField = value;
                    this.RaisePropertyChanged("RacunIzdajatelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Racun RacunPrejemnik {
            get {
                return this.RacunPrejemnikField;
            }
            set {
                if ((object.ReferenceEquals(this.RacunPrejemnikField, value) != true)) {
                    this.RacunPrejemnikField = value;
                    this.RaisePropertyChanged("RacunPrejemnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.TipTransakcije Tip {
            get {
                return this.TipField;
            }
            set {
                if ((this.TipField.Equals(value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Znesek {
            get {
                return this.ZnesekField;
            }
            set {
                if ((this.ZnesekField.Equals(value) != true)) {
                    this.ZnesekField = value;
                    this.RaisePropertyChanged("Znesek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Racun", Namespace="www.soa.com/projekt/racun/V4")]
    [System.SerializableAttribute()]
    public partial class Racun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stevilkaTRRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stevilkaTRR {
            get {
                return this.stevilkaTRRField;
            }
            set {
                if ((object.ReferenceEquals(this.stevilkaTRRField, value) != true)) {
                    this.stevilkaTRRField = value;
                    this.RaisePropertyChanged("stevilkaTRR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipTransakcije", Namespace="www.soa.com/projekt/tipTransakcije/V4")]
    public enum TipTransakcije : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        priliv = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        odliv = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
    [System.SerializableAttribute()]
    public partial class LastnaNapaka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SporociloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacija {
            get {
                return this.OperacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacijaField, value) != true)) {
                    this.OperacijaField = value;
                    this.RaisePropertyChanged("Operacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sporocilo {
            get {
                return this.SporociloField;
            }
            set {
                if ((object.ReferenceEquals(this.SporociloField, value) != true)) {
                    this.SporociloField = value;
                    this.RaisePropertyChanged("Sporocilo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eRacun", Namespace="www.soa.com/projekt/eRacun/V4")]
    [System.SerializableAttribute()]
    public partial class eRacun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AliJePlacanRacunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumIzdajeRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumPlacilaRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifikatorRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Racun RacunIzdajateljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Racun RacunPrejemnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RokPlacilaRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValutaZneskaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Postavka[] VsePostavkeNaRacunuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZnesekRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_racunaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AliJePlacanRacun {
            get {
                return this.AliJePlacanRacunField;
            }
            set {
                if ((this.AliJePlacanRacunField.Equals(value) != true)) {
                    this.AliJePlacanRacunField = value;
                    this.RaisePropertyChanged("AliJePlacanRacun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumIzdajeRacuna {
            get {
                return this.DatumIzdajeRacunaField;
            }
            set {
                if ((this.DatumIzdajeRacunaField.Equals(value) != true)) {
                    this.DatumIzdajeRacunaField = value;
                    this.RaisePropertyChanged("DatumIzdajeRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumPlacilaRacuna {
            get {
                return this.DatumPlacilaRacunaField;
            }
            set {
                if ((this.DatumPlacilaRacunaField.Equals(value) != true)) {
                    this.DatumPlacilaRacunaField = value;
                    this.RaisePropertyChanged("DatumPlacilaRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentifikatorRacuna {
            get {
                return this.IdentifikatorRacunaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifikatorRacunaField, value) != true)) {
                    this.IdentifikatorRacunaField = value;
                    this.RaisePropertyChanged("IdentifikatorRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivRacuna {
            get {
                return this.NazivRacunaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivRacunaField, value) != true)) {
                    this.NazivRacunaField = value;
                    this.RaisePropertyChanged("NazivRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Racun RacunIzdajatelj {
            get {
                return this.RacunIzdajateljField;
            }
            set {
                if ((object.ReferenceEquals(this.RacunIzdajateljField, value) != true)) {
                    this.RacunIzdajateljField = value;
                    this.RaisePropertyChanged("RacunIzdajatelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Racun RacunPrejemnik {
            get {
                return this.RacunPrejemnikField;
            }
            set {
                if ((object.ReferenceEquals(this.RacunPrejemnikField, value) != true)) {
                    this.RacunPrejemnikField = value;
                    this.RaisePropertyChanged("RacunPrejemnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RokPlacilaRacuna {
            get {
                return this.RokPlacilaRacunaField;
            }
            set {
                if ((this.RokPlacilaRacunaField.Equals(value) != true)) {
                    this.RokPlacilaRacunaField = value;
                    this.RaisePropertyChanged("RokPlacilaRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValutaZneska {
            get {
                return this.ValutaZneskaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValutaZneskaField, value) != true)) {
                    this.ValutaZneskaField = value;
                    this.RaisePropertyChanged("ValutaZneska");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Postavka[] VsePostavkeNaRacunu {
            get {
                return this.VsePostavkeNaRacunuField;
            }
            set {
                if ((object.ReferenceEquals(this.VsePostavkeNaRacunuField, value) != true)) {
                    this.VsePostavkeNaRacunuField = value;
                    this.RaisePropertyChanged("VsePostavkeNaRacunu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ZnesekRacuna {
            get {
                return this.ZnesekRacunaField;
            }
            set {
                if ((this.ZnesekRacunaField.Equals(value) != true)) {
                    this.ZnesekRacunaField = value;
                    this.RaisePropertyChanged("ZnesekRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_racuna {
            get {
                return this.id_racunaField;
            }
            set {
                if ((this.id_racunaField.Equals(value) != true)) {
                    this.id_racunaField = value;
                    this.RaisePropertyChanged("id_racuna");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Postavka", Namespace="www.soa.com/projekt/postavka/V4")]
    [System.SerializableAttribute()]
    public partial class Postavka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DavcnaStopnjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ZnesekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ZnesekDavekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DavcnaStopnja {
            get {
                return this.DavcnaStopnjaField;
            }
            set {
                if ((this.DavcnaStopnjaField.Equals(value) != true)) {
                    this.DavcnaStopnjaField = value;
                    this.RaisePropertyChanged("DavcnaStopnja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enota {
            get {
                return this.EnotaField;
            }
            set {
                if ((object.ReferenceEquals(this.EnotaField, value) != true)) {
                    this.EnotaField = value;
                    this.RaisePropertyChanged("Enota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Znesek {
            get {
                return this.ZnesekField;
            }
            set {
                if ((this.ZnesekField.Equals(value) != true)) {
                    this.ZnesekField = value;
                    this.RaisePropertyChanged("Znesek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ZnesekDavek {
            get {
                return this.ZnesekDavekField;
            }
            set {
                if ((this.ZnesekDavekField.Equals(value) != true)) {
                    this.ZnesekDavekField = value;
                    this.RaisePropertyChanged("ZnesekDavek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UstvarjenERacunResponse", Namespace="www.soa.com/projekt/ustvarjenERacunResponse/V4")]
    [System.SerializableAttribute()]
    public partial class UstvarjenERacunResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifikatorERacunaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentifikatorERacuna {
            get {
                return this.IdentifikatorERacunaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifikatorERacunaField, value) != true)) {
                    this.IdentifikatorERacunaField = value;
                    this.RaisePropertyChanged("IdentifikatorERacuna");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateERacun", Namespace="www.soa.com/projekt/TemplateERacun/V4")]
    [System.SerializableAttribute()]
    public partial class TemplateERacun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Racun RacunIzdajateljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValutaZneskaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.Bank.Postavka[] VsePostavkeNaRacunuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZnesekRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_templateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivRacuna {
            get {
                return this.NazivRacunaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivRacunaField, value) != true)) {
                    this.NazivRacunaField = value;
                    this.RaisePropertyChanged("NazivRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivTemplate {
            get {
                return this.NazivTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivTemplateField, value) != true)) {
                    this.NazivTemplateField = value;
                    this.RaisePropertyChanged("NazivTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Racun RacunIzdajatelj {
            get {
                return this.RacunIzdajateljField;
            }
            set {
                if ((object.ReferenceEquals(this.RacunIzdajateljField, value) != true)) {
                    this.RacunIzdajateljField = value;
                    this.RaisePropertyChanged("RacunIzdajatelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValutaZneska {
            get {
                return this.ValutaZneskaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValutaZneskaField, value) != true)) {
                    this.ValutaZneskaField = value;
                    this.RaisePropertyChanged("ValutaZneska");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.Bank.Postavka[] VsePostavkeNaRacunu {
            get {
                return this.VsePostavkeNaRacunuField;
            }
            set {
                if ((object.ReferenceEquals(this.VsePostavkeNaRacunuField, value) != true)) {
                    this.VsePostavkeNaRacunuField = value;
                    this.RaisePropertyChanged("VsePostavkeNaRacunu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ZnesekRacuna {
            get {
                return this.ZnesekRacunaField;
            }
            set {
                if ((this.ZnesekRacunaField.Equals(value) != true)) {
                    this.ZnesekRacunaField = value;
                    this.RaisePropertyChanged("ZnesekRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_template {
            get {
                return this.id_templateField;
            }
            set {
                if ((this.id_templateField.Equals(value) != true)) {
                    this.id_templateField = value;
                    this.RaisePropertyChanged("id_template");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.soa.com/projekt/V3", ConfigurationName="Bank.Banka")]
    public interface Banka {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/UstvariRacun", ReplyAction="www.soa.com/projekt/V3/Banka/UstvariRacunResponse")]
        ApartmentComplexServiceLibraryV1.Bank.UstvarjenRacunResponse UstvariRacun(ApartmentComplexServiceLibraryV1.Bank.Komitent komitent);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/UstvariRacun", ReplyAction="www.soa.com/projekt/V3/Banka/UstvariRacunResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.UstvarjenRacunResponse> UstvariRacunAsync(ApartmentComplexServiceLibraryV1.Bank.Komitent komitent);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledTransakcij", ReplyAction="www.soa.com/projekt/V3/Banka/PregledTransakcijResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledTransakcijLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.Transakcija[] PregledTransakcij(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledTransakcij", ReplyAction="www.soa.com/projekt/V3/Banka/PregledTransakcijResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.Transakcija[]> PregledTransakcijAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledStanja", ReplyAction="www.soa.com/projekt/V3/Banka/PregledStanjaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledStanjaLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        decimal PregledStanja(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledStanja", ReplyAction="www.soa.com/projekt/V3/Banka/PregledStanjaResponse")]
        System.Threading.Tasks.Task<decimal> PregledStanjaAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PologSredstev", ReplyAction="www.soa.com/projekt/V3/Banka/PologSredstevResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PologSredstevLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        void PologSredstev(string trr, decimal znesekPologa);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PologSredstev", ReplyAction="www.soa.com/projekt/V3/Banka/PologSredstevResponse")]
        System.Threading.Tasks.Task PologSredstevAsync(string trr, decimal znesekPologa);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PrenosSredstevMedRacuni", ReplyAction="www.soa.com/projekt/V3/Banka/PrenosSredstevMedRacuniResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PrenosSredstevMedRacuniLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        void PrenosSredstevMedRacuni(string trr_posiljatelj, string pin_posiljatelj, string trr_prejemnik, decimal znesekPrenosa);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PrenosSredstevMedRacuni", ReplyAction="www.soa.com/projekt/V3/Banka/PrenosSredstevMedRacuniResponse")]
        System.Threading.Tasks.Task PrenosSredstevMedRacuniAsync(string trr_posiljatelj, string pin_posiljatelj, string trr_prejemnik, decimal znesekPrenosa);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/UstvarjanjeERacuna", ReplyAction="www.soa.com/projekt/V3/Banka/UstvarjanjeERacunaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/UstvarjanjeERacunaLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.UstvarjenERacunResponse UstvarjanjeERacuna(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.eRacun eRacun);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/UstvarjanjeERacuna", ReplyAction="www.soa.com/projekt/V3/Banka/UstvarjanjeERacunaResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.UstvarjenERacunResponse> UstvarjanjeERacunaAsync(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.eRacun eRacun);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PlaciloERacuna", ReplyAction="www.soa.com/projekt/V3/Banka/PlaciloERacunaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PlaciloERacunaLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        void PlaciloERacuna(string trr, string pin, string identifikatorRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PlaciloERacuna", ReplyAction="www.soa.com/projekt/V3/Banka/PlaciloERacunaResponse")]
        System.Threading.Tasks.Task PlaciloERacunaAsync(string trr, string pin, string identifikatorRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIdentifikator", ReplyAction="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIdentifikatorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIdentifikatorLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun VrniSpecificniERacunIdentifikator(string trr, string pin, string identifikatorRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIdentifikator", ReplyAction="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIdentifikatorResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun> VrniSpecificniERacunIdentifikatorAsync(string trr, string pin, string identifikatorRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIzdajatelj", ReplyAction="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIzdajateljResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIzdajateljLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun VrniSpecificniERacunIzdajatelj(string trr, string pin, int idRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIzdajatelj", ReplyAction="www.soa.com/projekt/V3/Banka/VrniSpecificniERacunIzdajateljResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun> VrniSpecificniERacunIzdajateljAsync(string trr, string pin, int idRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunov", ReplyAction="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledNeplacanihERacunov(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunov", ReplyAction="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledNeplacanihERacunovAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovIzdajatelj", ReplyAction="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovIzdajateljResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovIzdajateljLastnaNapakaFault" +
            "", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledNeplacanihERacunovIzdajatelj(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovIzdajatelj", ReplyAction="www.soa.com/projekt/V3/Banka/PregledNeplacanihERacunovIzdajateljResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledNeplacanihERacunovIzdajateljAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/pregledNeplacanihERacunovPrejemnik", ReplyAction="www.soa.com/projekt/V3/Banka/pregledNeplacanihERacunovPrejemnikResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/pregledNeplacanihERacunovPrejemnikLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun[] pregledNeplacanihERacunovPrejemnik(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/pregledNeplacanihERacunovPrejemnik", ReplyAction="www.soa.com/projekt/V3/Banka/pregledNeplacanihERacunovPrejemnikResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> pregledNeplacanihERacunovPrejemnikAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunov", ReplyAction="www.soa.com/projekt/V3/Banka/PregledVsehERacunovResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledVsehERacunov(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunov", ReplyAction="www.soa.com/projekt/V3/Banka/PregledVsehERacunovResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledVsehERacunovAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovIzdajatelj", ReplyAction="www.soa.com/projekt/V3/Banka/PregledVsehERacunovIzdajateljResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovIzdajateljLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledVsehERacunovIzdajatelj(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovIzdajatelj", ReplyAction="www.soa.com/projekt/V3/Banka/PregledVsehERacunovIzdajateljResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledVsehERacunovIzdajateljAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovPrejemnik", ReplyAction="www.soa.com/projekt/V3/Banka/PregledVsehERacunovPrejemnikResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovPrejemnikLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledVsehERacunovPrejemnik(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PregledVsehERacunovPrejemnik", ReplyAction="www.soa.com/projekt/V3/Banka/PregledVsehERacunovPrejemnikResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledVsehERacunovPrejemnikAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PlaciloSPlacilnoKartico", ReplyAction="www.soa.com/projekt/V3/Banka/PlaciloSPlacilnoKarticoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PlaciloSPlacilnoKarticoLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        void PlaciloSPlacilnoKartico(string trr_placnik, string pin_placnik, decimal znesek, string trr_prejemnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PlaciloSPlacilnoKartico", ReplyAction="www.soa.com/projekt/V3/Banka/PlaciloSPlacilnoKarticoResponse")]
        System.Threading.Tasks.Task PlaciloSPlacilnoKarticoAsync(string trr_placnik, string pin_placnik, decimal znesek, string trr_prejemnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/UstvariTemplateERacun", ReplyAction="www.soa.com/projekt/V3/Banka/UstvariTemplateERacunResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/UstvariTemplateERacunLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        void UstvariTemplateERacun(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.TemplateERacun TemplateERacun);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/UstvariTemplateERacun", ReplyAction="www.soa.com/projekt/V3/Banka/UstvariTemplateERacunResponse")]
        System.Threading.Tasks.Task UstvariTemplateERacunAsync(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.TemplateERacun TemplateERacun);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PridobiTemplatesERacun", ReplyAction="www.soa.com/projekt/V3/Banka/PridobiTemplatesERacunResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PridobiTemplatesERacunLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.TemplateERacun[] PridobiTemplatesERacun(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PridobiTemplatesERacun", ReplyAction="www.soa.com/projekt/V3/Banka/PridobiTemplatesERacunResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.TemplateERacun[]> PridobiTemplatesERacunAsync(string trr, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PridobiSpecificniTemplate", ReplyAction="www.soa.com/projekt/V3/Banka/PridobiSpecificniTemplateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.Bank.LastnaNapaka), Action="www.soa.com/projekt/V3/Banka/PridobiSpecificniTemplateLastnaNapakaFault", Name="LastnaNapaka", Namespace="http://projekt/SOA/V3")]
        ApartmentComplexServiceLibraryV1.Bank.eRacun PridobiSpecificniTemplate(string trr, string pin, int id_template);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.soa.com/projekt/V3/Banka/PridobiSpecificniTemplate", ReplyAction="www.soa.com/projekt/V3/Banka/PridobiSpecificniTemplateResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun> PridobiSpecificniTemplateAsync(string trr, string pin, int id_template);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankaChannel : ApartmentComplexServiceLibraryV1.Bank.Banka, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankaClient : System.ServiceModel.ClientBase<ApartmentComplexServiceLibraryV1.Bank.Banka>, ApartmentComplexServiceLibraryV1.Bank.Banka {
        
        public BankaClient() {
        }
        
        public BankaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.UstvarjenRacunResponse UstvariRacun(ApartmentComplexServiceLibraryV1.Bank.Komitent komitent) {
            return base.Channel.UstvariRacun(komitent);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.UstvarjenRacunResponse> UstvariRacunAsync(ApartmentComplexServiceLibraryV1.Bank.Komitent komitent) {
            return base.Channel.UstvariRacunAsync(komitent);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.Transakcija[] PregledTransakcij(string trr, string pin) {
            return base.Channel.PregledTransakcij(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.Transakcija[]> PregledTransakcijAsync(string trr, string pin) {
            return base.Channel.PregledTransakcijAsync(trr, pin);
        }
        
        public decimal PregledStanja(string trr, string pin) {
            return base.Channel.PregledStanja(trr, pin);
        }
        
        public System.Threading.Tasks.Task<decimal> PregledStanjaAsync(string trr, string pin) {
            return base.Channel.PregledStanjaAsync(trr, pin);
        }
        
        public void PologSredstev(string trr, decimal znesekPologa) {
            base.Channel.PologSredstev(trr, znesekPologa);
        }
        
        public System.Threading.Tasks.Task PologSredstevAsync(string trr, decimal znesekPologa) {
            return base.Channel.PologSredstevAsync(trr, znesekPologa);
        }
        
        public void PrenosSredstevMedRacuni(string trr_posiljatelj, string pin_posiljatelj, string trr_prejemnik, decimal znesekPrenosa) {
            base.Channel.PrenosSredstevMedRacuni(trr_posiljatelj, pin_posiljatelj, trr_prejemnik, znesekPrenosa);
        }
        
        public System.Threading.Tasks.Task PrenosSredstevMedRacuniAsync(string trr_posiljatelj, string pin_posiljatelj, string trr_prejemnik, decimal znesekPrenosa) {
            return base.Channel.PrenosSredstevMedRacuniAsync(trr_posiljatelj, pin_posiljatelj, trr_prejemnik, znesekPrenosa);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.UstvarjenERacunResponse UstvarjanjeERacuna(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.eRacun eRacun) {
            return base.Channel.UstvarjanjeERacuna(trr, pin, eRacun);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.UstvarjenERacunResponse> UstvarjanjeERacunaAsync(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.eRacun eRacun) {
            return base.Channel.UstvarjanjeERacunaAsync(trr, pin, eRacun);
        }
        
        public void PlaciloERacuna(string trr, string pin, string identifikatorRacuna) {
            base.Channel.PlaciloERacuna(trr, pin, identifikatorRacuna);
        }
        
        public System.Threading.Tasks.Task PlaciloERacunaAsync(string trr, string pin, string identifikatorRacuna) {
            return base.Channel.PlaciloERacunaAsync(trr, pin, identifikatorRacuna);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun VrniSpecificniERacunIdentifikator(string trr, string pin, string identifikatorRacuna) {
            return base.Channel.VrniSpecificniERacunIdentifikator(trr, pin, identifikatorRacuna);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun> VrniSpecificniERacunIdentifikatorAsync(string trr, string pin, string identifikatorRacuna) {
            return base.Channel.VrniSpecificniERacunIdentifikatorAsync(trr, pin, identifikatorRacuna);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun VrniSpecificniERacunIzdajatelj(string trr, string pin, int idRacuna) {
            return base.Channel.VrniSpecificniERacunIzdajatelj(trr, pin, idRacuna);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun> VrniSpecificniERacunIzdajateljAsync(string trr, string pin, int idRacuna) {
            return base.Channel.VrniSpecificniERacunIzdajateljAsync(trr, pin, idRacuna);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledNeplacanihERacunov(string trr, string pin) {
            return base.Channel.PregledNeplacanihERacunov(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledNeplacanihERacunovAsync(string trr, string pin) {
            return base.Channel.PregledNeplacanihERacunovAsync(trr, pin);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledNeplacanihERacunovIzdajatelj(string trr, string pin) {
            return base.Channel.PregledNeplacanihERacunovIzdajatelj(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledNeplacanihERacunovIzdajateljAsync(string trr, string pin) {
            return base.Channel.PregledNeplacanihERacunovIzdajateljAsync(trr, pin);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun[] pregledNeplacanihERacunovPrejemnik(string trr, string pin) {
            return base.Channel.pregledNeplacanihERacunovPrejemnik(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> pregledNeplacanihERacunovPrejemnikAsync(string trr, string pin) {
            return base.Channel.pregledNeplacanihERacunovPrejemnikAsync(trr, pin);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledVsehERacunov(string trr, string pin) {
            return base.Channel.PregledVsehERacunov(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledVsehERacunovAsync(string trr, string pin) {
            return base.Channel.PregledVsehERacunovAsync(trr, pin);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledVsehERacunovIzdajatelj(string trr, string pin) {
            return base.Channel.PregledVsehERacunovIzdajatelj(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledVsehERacunovIzdajateljAsync(string trr, string pin) {
            return base.Channel.PregledVsehERacunovIzdajateljAsync(trr, pin);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun[] PregledVsehERacunovPrejemnik(string trr, string pin) {
            return base.Channel.PregledVsehERacunovPrejemnik(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun[]> PregledVsehERacunovPrejemnikAsync(string trr, string pin) {
            return base.Channel.PregledVsehERacunovPrejemnikAsync(trr, pin);
        }
        
        public void PlaciloSPlacilnoKartico(string trr_placnik, string pin_placnik, decimal znesek, string trr_prejemnika) {
            base.Channel.PlaciloSPlacilnoKartico(trr_placnik, pin_placnik, znesek, trr_prejemnika);
        }
        
        public System.Threading.Tasks.Task PlaciloSPlacilnoKarticoAsync(string trr_placnik, string pin_placnik, decimal znesek, string trr_prejemnika) {
            return base.Channel.PlaciloSPlacilnoKarticoAsync(trr_placnik, pin_placnik, znesek, trr_prejemnika);
        }
        
        public void UstvariTemplateERacun(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.TemplateERacun TemplateERacun) {
            base.Channel.UstvariTemplateERacun(trr, pin, TemplateERacun);
        }
        
        public System.Threading.Tasks.Task UstvariTemplateERacunAsync(string trr, string pin, ApartmentComplexServiceLibraryV1.Bank.TemplateERacun TemplateERacun) {
            return base.Channel.UstvariTemplateERacunAsync(trr, pin, TemplateERacun);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.TemplateERacun[] PridobiTemplatesERacun(string trr, string pin) {
            return base.Channel.PridobiTemplatesERacun(trr, pin);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.TemplateERacun[]> PridobiTemplatesERacunAsync(string trr, string pin) {
            return base.Channel.PridobiTemplatesERacunAsync(trr, pin);
        }
        
        public ApartmentComplexServiceLibraryV1.Bank.eRacun PridobiSpecificniTemplate(string trr, string pin, int id_template) {
            return base.Channel.PridobiSpecificniTemplate(trr, pin, id_template);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.Bank.eRacun> PridobiSpecificniTemplateAsync(string trr, string pin, int id_template) {
            return base.Channel.PridobiSpecificniTemplateAsync(trr, pin, id_template);
        }
    }
}
