-- MySQL Script generated by MySQL Workbench
-- Mon Dec  8 19:28:04 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apartma2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apartma2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apartma2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `apartma2` ;

-- -----------------------------------------------------
-- Table `apartma2`.`apartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`apartment` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`apartment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `latitude` FLOAT(10,6) NULL,
  `longitude` FLOAT(10,6) NULL,
  `pet_friendly` TINYINT(1) NULL,
  `no_king_beds` INT NULL,
  `no_single_beds` INT NULL,
  `no_extra_beds` INT NULL,
  `internet` TINYINT(1) NULL,
  `air_conditioning` TINYINT(1) NULL,
  `tv` TINYINT(1) NULL,
  `kitchen` TINYINT(1) NULL,
  `class_stars` INT NULL,
  `balcony` TINYINT(1) NULL,
  `accessible` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`customer` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(90) NULL,
  `address` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`review` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NULL,
  `grade` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_apartment_idx` (`apartment_id` ASC),
  INDEX `fk_comments_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_comments_apartment`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `apartma2`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `apartma2`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`payment_method` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(45) NULL,
  `bank_payment` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`arrangement_package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`arrangement_package` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`arrangement_package` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `max_resevations` VARCHAR(45) NULL,
  `valid_from` INT NULL,
  `valid_to` INT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`discounts` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `valid_from` INT NOT NULL,
  `valid_to` INT NOT NULL,
  `discount_percentage` FLOAT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`booking` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_from` INT NOT NULL,
  `date_to` INT NOT NULL,
  `apartment_idapartment` INT NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  `arrangement_package_id` INT NULL,
  `discounts_id` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Booked_apartment1_idx` (`apartment_idapartment` ASC),
  INDEX `fk_Booked_customer1_idx` (`customer_idcustomer` ASC),
  INDEX `fk_Booked_payment_method1_idx` (`payment_method_id` ASC),
  INDEX `fk_booked_arrangement_package1_idx` (`arrangement_package_id` ASC),
  INDEX `fk_booked_discounts1_idx` (`discounts_id` ASC),
  CONSTRAINT `fk_Booked_apartment1`
    FOREIGN KEY (`apartment_idapartment`)
    REFERENCES `apartma2`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booked_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `apartma2`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booked_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `apartma2`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booked_arrangement_package1`
    FOREIGN KEY (`arrangement_package_id`)
    REFERENCES `apartma2`.`arrangement_package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booked_discounts1`
    FOREIGN KEY (`discounts_id`)
    REFERENCES `apartma2`.`discounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`arrangement_package_has_apartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`arrangement_package_has_apartment` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`arrangement_package_has_apartment` (
  `arrangement_package_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`arrangement_package_id`, `apartment_id`),
  INDEX `fk_arrangement_package_has_apartment_apartment1_idx` (`apartment_id` ASC),
  INDEX `fk_arrangement_package_has_apartment_arrangement_package1_idx` (`arrangement_package_id` ASC),
  CONSTRAINT `fk_arrangement_package_has_apartment_arrangement_package1`
    FOREIGN KEY (`arrangement_package_id`)
    REFERENCES `apartma2`.`arrangement_package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arrangement_package_has_apartment_apartment1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `apartma2`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apartma2`.`apartment_has_discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apartma2`.`apartment_has_discounts` ;

CREATE TABLE IF NOT EXISTS `apartma2`.`apartment_has_discounts` (
  `apartment_id` INT NOT NULL,
  `discounts_id` INT NOT NULL,
  PRIMARY KEY (`apartment_id`, `discounts_id`),
  INDEX `fk_apartment_has_discounts_discounts1_idx` (`discounts_id` ASC),
  INDEX `fk_apartment_has_discounts_apartment1_idx` (`apartment_id` ASC),
  CONSTRAINT `fk_apartment_has_discounts_apartment1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `apartma2`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apartment_has_discounts_discounts1`
    FOREIGN KEY (`discounts_id`)
    REFERENCES `apartma2`.`discounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
