//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentComplexServiceLibraryV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public int date_from { get; set; }
        public int date_to { get; set; }
        public int apartment_idapartment { get; set; }
        public string customer_trr { get; set; }
        public int payment_method_id { get; set; }
        public Nullable<int> arrangement_package_id { get; set; }
        public Nullable<int> discounts_id { get; set; }
        public string status { get; set; }
    
        public virtual apartment apartment { get; set; }
        public virtual arrangement_package arrangement_package { get; set; }
        public virtual discount discount { get; set; }
        public virtual payment_method payment_method { get; set; }
    }
}
