//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentComplexServiceLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartment
    {
        public apartment()
        {
            this.bookings = new HashSet<booking>();
            this.reviews = new HashSet<review>();
            this.discounts = new HashSet<discount>();
            this.arrangement_package = new HashSet<arrangement_package>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<bool> pet_friendly { get; set; }
        public Nullable<int> no_king_beds { get; set; }
        public Nullable<int> no_single_beds { get; set; }
        public Nullable<int> no_extra_beds { get; set; }
        public Nullable<bool> internet { get; set; }
        public Nullable<bool> air_conditioning { get; set; }
        public Nullable<bool> tv { get; set; }
        public Nullable<bool> kitchen { get; set; }
        public Nullable<int> class_stars { get; set; }
        public Nullable<bool> balcony { get; set; }
        public Nullable<bool> accessible { get; set; }
    
        public virtual ICollection<booking> bookings { get; set; }
        public virtual ICollection<review> reviews { get; set; }
        public virtual ICollection<discount> discounts { get; set; }
        public virtual ICollection<arrangement_package> arrangement_package { get; set; }
    }
}
