//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentAdministrationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soa.apartments.net/v0_1/ApartmentAdministrationService", ConfigurationName="ApartmentAdministrationService.ApartmentAdministrationService")]
    public interface ApartmentAdministrationService
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message AddApartmentRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/AddApartment")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.AddApartmentResponse AddApartment(ApartmentAdministrationService.AddApartmentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message FindApartmentRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/FindApartment")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.FindApartmentResponse FindApartment(ApartmentAdministrationService.FindApartmentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message UpdateApartmentRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/UpdateApartment")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.UpdateApartmentResponse UpdateApartment(ApartmentAdministrationService.UpdateApartmentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message DeleteApartmentRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/DeleteApartment")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.DeleteApartmentResponse DeleteApartment(ApartmentAdministrationService.DeleteApartmentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message AddBookingRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/AddBooking")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.AddBookingResponse AddBooking(ApartmentAdministrationService.AddBookingRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message GetBookingRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/GetBooking")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.GetBookingResponse GetBooking(ApartmentAdministrationService.GetBookingRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message UpdateBookingRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/UpdateBooking")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.UpdateBookingResponse UpdateBooking(ApartmentAdministrationService.UpdateBookingRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message AddPackageArrangementsRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/AddPackageArrangeme" +
            "nts")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.AddPackageArrangementsResponse AddPackageArrangements(ApartmentAdministrationService.AddPackageArrangementsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message GetPackageArrangementsRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/GetPackageArrangeme" +
            "nts")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.GetPackageArrangementsResponse GetPackageArrangements(ApartmentAdministrationService.GetPackageArrangementsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message UpdatePackageArrangementsRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/UpdatePackageArrang" +
            "ements")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.UpdatePackageArrangementsResponse UpdatePackageArrangements(ApartmentAdministrationService.UpdatePackageArrangementsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message DeletePackageArrangementsRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/DeletePackageArrang" +
            "ements")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.DeletePackageArrangementsResponse DeletePackageArrangements(ApartmentAdministrationService.DeletePackageArrangementsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message AddDiscountRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/AddDiscount")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.AddDiscountResponse AddDiscount(ApartmentAdministrationService.AddDiscountRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message UpdateDiscountRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/UpdateDiscount")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.UpdateDiscountResponse UpdateDiscount(ApartmentAdministrationService.UpdateDiscountRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message DeleteDiscountRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/DeleteDiscount")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.DeleteDiscountResponse DeleteDiscount(ApartmentAdministrationService.DeleteDiscountRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message UpdateComplexInfoRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/UpdateComplexInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.UpdateComplexInfoResponse UpdateComplexInfo(ApartmentAdministrationService.UpdateComplexInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message AddCustomerRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/AddCustomer")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.AddCustomerResponse AddCustomer(ApartmentAdministrationService.AddCustomerRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message FindCustomerRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/FindCustomer")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.FindCustomerResponse FindCustomer(ApartmentAdministrationService.FindCustomerRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message UpdateCustomerRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/UpdateCustomer")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.UpdateCustomerResponse UpdateCustomer(ApartmentAdministrationService.UpdateCustomerRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soa.apartments.net/v0_1/administration_messages) of message DeleteCustomerRequest does not match the default value (http://soa.apartments.net/v0_1/ApartmentAdministrationService)
        [System.ServiceModel.OperationContractAttribute(Action="http://soa.apartments.net/v0_1/ApartmentAdministrationService/DeleteCustomer")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ApartmentAdministrationService.DeleteCustomerResponse DeleteCustomer(ApartmentAdministrationService.DeleteCustomerRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class apartment
    {
        
        private int idField;
        
        private string numberField;
        
        private string titleField;
        
        private string descriptionField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private int no_king_bedsField;
        
        private int no_single_bedsField;
        
        private int no_extra_bedsField;
        
        private bool pet_friendlyField;
        
        private bool internetField;
        
        private bool air_conditioningField;
        
        private bool tvField;
        
        private bool kitchenField;
        
        private bool accessibleField;
        
        private int class_starsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int no_king_beds
        {
            get
            {
                return this.no_king_bedsField;
            }
            set
            {
                this.no_king_bedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int no_single_beds
        {
            get
            {
                return this.no_single_bedsField;
            }
            set
            {
                this.no_single_bedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int no_extra_beds
        {
            get
            {
                return this.no_extra_bedsField;
            }
            set
            {
                this.no_extra_bedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool pet_friendly
        {
            get
            {
                return this.pet_friendlyField;
            }
            set
            {
                this.pet_friendlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool internet
        {
            get
            {
                return this.internetField;
            }
            set
            {
                this.internetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool air_conditioning
        {
            get
            {
                return this.air_conditioningField;
            }
            set
            {
                this.air_conditioningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool tv
        {
            get
            {
                return this.tvField;
            }
            set
            {
                this.tvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool kitchen
        {
            get
            {
                return this.kitchenField;
            }
            set
            {
                this.kitchenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool accessible
        {
            get
            {
                return this.accessibleField;
            }
            set
            {
                this.accessibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int class_stars
        {
            get
            {
                return this.class_starsField;
            }
            set
            {
                this.class_starsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class complex_info
    {
        
        private string titleField;
        
        private string descriptionField;
        
        private int capacityField;
        
        private int number_of_apartmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int number_of_apartments
        {
            get
            {
                return this.number_of_apartmentsField;
            }
            set
            {
                this.number_of_apartmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class arrangement_package
    {
        
        private int idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int max_reservationsField;
        
        private int valid_fromField;
        
        private int valid_toField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int max_reservations
        {
            get
            {
                return this.max_reservationsField;
            }
            set
            {
                this.max_reservationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int valid_from
        {
            get
            {
                return this.valid_fromField;
            }
            set
            {
                this.valid_fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int valid_to
        {
            get
            {
                return this.valid_toField;
            }
            set
            {
                this.valid_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class discount
    {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int valid_fromField;
        
        private int valid_toField;
        
        private double discount_percentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int valid_from
        {
            get
            {
                return this.valid_fromField;
            }
            set
            {
                this.valid_fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int valid_to
        {
            get
            {
                return this.valid_toField;
            }
            set
            {
                this.valid_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double discount_percentage
        {
            get
            {
                return this.discount_percentageField;
            }
            set
            {
                this.discount_percentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class payment_method
    {
        
        private int idField;
        
        private string card_numberField;
        
        private bool bank_paymentField;
        
        private bool bank_paymentFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string card_number
        {
            get
            {
                return this.card_numberField;
            }
            set
            {
                this.card_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool bank_payment
        {
            get
            {
                return this.bank_paymentField;
            }
            set
            {
                this.bank_paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bank_paymentSpecified
        {
            get
            {
                return this.bank_paymentFieldSpecified;
            }
            set
            {
                this.bank_paymentFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class customer
    {
        
        private int idField;
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string emailField;
        
        private string addressField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string first_name
        {
            get
            {
                return this.first_nameField;
            }
            set
            {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string last_name
        {
            get
            {
                return this.last_nameField;
            }
            set
            {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public partial class booking
    {
        
        private int idField;
        
        private int date_fromField;
        
        private int date_toField;
        
        private booking_status statusField;
        
        private apartment apartmentField;
        
        private customer customerField;
        
        private payment_method paymentField;
        
        private discount discountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int date_from
        {
            get
            {
                return this.date_fromField;
            }
            set
            {
                this.date_fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int date_to
        {
            get
            {
                return this.date_toField;
            }
            set
            {
                this.date_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public booking_status status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public apartment apartment
        {
            get
            {
                return this.apartmentField;
            }
            set
            {
                this.apartmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public customer customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public payment_method payment
        {
            get
            {
                return this.paymentField;
            }
            set
            {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public discount discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.apartments.net/v0_1/types")]
    public enum booking_status
    {
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        reserved,
        
        /// <remarks/>
        completed,
        
        /// <remarks/>
        cancelled,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddApartmentRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddApartmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.apartment apartment;
        
        public AddApartmentRequest()
        {
        }
        
        public AddApartmentRequest(ApartmentAdministrationService.apartment apartment)
        {
            this.apartment = apartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddApartmentResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddApartmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public AddApartmentResponse()
        {
        }
        
        public AddApartmentResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindApartmentRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class FindApartmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int apartment_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number_of_beds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public FindApartmentRequest()
        {
        }
        
        public FindApartmentRequest(int apartment_number, int number_of_beds, int id)
        {
            this.apartment_number = apartment_number;
            this.number_of_beds = number_of_beds;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindApartmentResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class FindApartmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.apartment apartment;
        
        public FindApartmentResponse()
        {
        }
        
        public FindApartmentResponse(ApartmentAdministrationService.apartment apartment)
        {
            this.apartment = apartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateApartmentRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateApartmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.apartment apartment;
        
        public UpdateApartmentRequest()
        {
        }
        
        public UpdateApartmentRequest(ApartmentAdministrationService.apartment apartment)
        {
            this.apartment = apartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateApartmentResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateApartmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public UpdateApartmentResponse()
        {
        }
        
        public UpdateApartmentResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteApartmentRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeleteApartmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.apartment apartment;
        
        public DeleteApartmentRequest()
        {
        }
        
        public DeleteApartmentRequest(ApartmentAdministrationService.apartment apartment)
        {
            this.apartment = apartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteApartmentResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeleteApartmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public DeleteApartmentResponse()
        {
        }
        
        public DeleteApartmentResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBookingRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddBookingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int apartment_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int date_from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int date_to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int package_arrangment_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string discount_code;
        
        public AddBookingRequest()
        {
        }
        
        public AddBookingRequest(int user_id, int apartment_id, int date_from, int date_to, int package_arrangment_id, string discount_code)
        {
            this.user_id = user_id;
            this.apartment_id = apartment_id;
            this.date_from = date_from;
            this.date_to = date_to;
            this.package_arrangment_id = package_arrangment_id;
            this.discount_code = discount_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBookingResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddBookingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool booking_status;
        
        public AddBookingResponse()
        {
        }
        
        public AddBookingResponse(bool booking_status)
        {
            this.booking_status = booking_status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class GetBookingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int apartment_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int date_from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int date_to;
        
        public GetBookingRequest()
        {
        }
        
        public GetBookingRequest(int id, int user_id, int apartment_id, int date_from, int date_to)
        {
            this.id = id;
            this.user_id = user_id;
            this.apartment_id = apartment_id;
            this.date_from = date_from;
            this.date_to = date_to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class GetBookingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.booking booking;
        
        public GetBookingResponse()
        {
        }
        
        public GetBookingResponse(ApartmentAdministrationService.booking booking)
        {
            this.booking = booking;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateBookingRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateBookingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.booking booking;
        
        public UpdateBookingRequest()
        {
        }
        
        public UpdateBookingRequest(ApartmentAdministrationService.booking booking)
        {
            this.booking = booking;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateBookingResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateBookingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public UpdateBookingResponse()
        {
        }
        
        public UpdateBookingResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPackageArrangementRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddPackageArrangementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.arrangement_package package_arrangements;
        
        public AddPackageArrangementsRequest()
        {
        }
        
        public AddPackageArrangementsRequest(ApartmentAdministrationService.arrangement_package package_arrangements)
        {
            this.package_arrangements = package_arrangements;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPackageArrangementResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddPackageArrangementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public AddPackageArrangementsResponse()
        {
        }
        
        public AddPackageArrangementsResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackageArrangementRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class GetPackageArrangementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int date_from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int date_to;
        
        public GetPackageArrangementsRequest()
        {
        }
        
        public GetPackageArrangementsRequest(int date_from, int date_to)
        {
            this.date_from = date_from;
            this.date_to = date_to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackageArrangementResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class GetPackageArrangementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arrangments_result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.arrangement_package[] arrangments_result;
        
        public GetPackageArrangementsResponse()
        {
        }
        
        public GetPackageArrangementsResponse(ApartmentAdministrationService.arrangement_package[] arrangments_result)
        {
            this.arrangments_result = arrangments_result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePackageArrangementRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdatePackageArrangementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.arrangement_package package_arrangements;
        
        public UpdatePackageArrangementsRequest()
        {
        }
        
        public UpdatePackageArrangementsRequest(ApartmentAdministrationService.arrangement_package package_arrangements)
        {
            this.package_arrangements = package_arrangements;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePackageArrangementResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdatePackageArrangementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public UpdatePackageArrangementsResponse()
        {
        }
        
        public UpdatePackageArrangementsResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePackageArrangementRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeletePackageArrangementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.arrangement_package package_arrangements;
        
        public DeletePackageArrangementsRequest()
        {
        }
        
        public DeletePackageArrangementsRequest(ApartmentAdministrationService.arrangement_package package_arrangements)
        {
            this.package_arrangements = package_arrangements;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePackageArrangementResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeletePackageArrangementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public DeletePackageArrangementsResponse()
        {
        }
        
        public DeletePackageArrangementsResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDiscountRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddDiscountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.discount discounts;
        
        public AddDiscountRequest()
        {
        }
        
        public AddDiscountRequest(ApartmentAdministrationService.discount discounts)
        {
            this.discounts = discounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDiscountResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddDiscountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public AddDiscountResponse()
        {
        }
        
        public AddDiscountResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDiscountRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateDiscountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.discount discounts;
        
        public UpdateDiscountRequest()
        {
        }
        
        public UpdateDiscountRequest(ApartmentAdministrationService.discount discounts)
        {
            this.discounts = discounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDiscountResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateDiscountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public UpdateDiscountResponse()
        {
        }
        
        public UpdateDiscountResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDiscountRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeleteDiscountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.discount discounts;
        
        public DeleteDiscountRequest()
        {
        }
        
        public DeleteDiscountRequest(ApartmentAdministrationService.discount discounts)
        {
            this.discounts = discounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDiscountResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeleteDiscountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public DeleteDiscountResponse()
        {
        }
        
        public DeleteDiscountResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateComplexInfoRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateComplexInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.complex_info complex;
        
        public UpdateComplexInfoRequest()
        {
        }
        
        public UpdateComplexInfoRequest(ApartmentAdministrationService.complex_info complex)
        {
            this.complex = complex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateComplexInfoResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateComplexInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public UpdateComplexInfoResponse()
        {
        }
        
        public UpdateComplexInfoResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCustomerRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.customer customer;
        
        public AddCustomerRequest()
        {
        }
        
        public AddCustomerRequest(ApartmentAdministrationService.customer customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCustomerResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class AddCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public AddCustomerResponse()
        {
        }
        
        public AddCustomerResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class FindCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string first_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tax_number;
        
        public FindCustomerRequest()
        {
        }
        
        public FindCustomerRequest(string id, string first_name, string last_name, string tax_number)
        {
            this.id = id;
            this.first_name = first_name;
            this.last_name = last_name;
            this.tax_number = tax_number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class FindCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.customer customer;
        
        public FindCustomerResponse()
        {
        }
        
        public FindCustomerResponse(ApartmentAdministrationService.customer customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.customer customer;
        
        public UpdateCustomerRequest()
        {
        }
        
        public UpdateCustomerRequest(ApartmentAdministrationService.customer customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class UpdateCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public UpdateCustomerResponse()
        {
        }
        
        public UpdateCustomerResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCustomerRequest", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeleteCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApartmentAdministrationService.customer customer;
        
        public DeleteCustomerRequest()
        {
        }
        
        public DeleteCustomerRequest(ApartmentAdministrationService.customer customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCustomerResponse", WrapperNamespace="http://soa.apartments.net/v0_1/administration_messages", IsWrapped=true)]
    public partial class DeleteCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.apartments.net/v0_1/administration_messages", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public DeleteCustomerResponse()
        {
        }
        
        public DeleteCustomerResponse(bool status)
        {
            this.status = status;
        }
    }
}
