//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentComplexServiceLibraryV1.AquaPark {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dogodek", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    public partial class Dogodek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumDogodkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDogodkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.AquaPark.KomentarDogodka[] KomentarDogodkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.AquaPark.LokacijaDogodka LokacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxSteviloPrijavField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivDogodkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PovprecnaOcenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.AquaPark.TipDogodka TipDogodkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumDogodka {
            get {
                return this.DatumDogodkaField;
            }
            set {
                if ((this.DatumDogodkaField.Equals(value) != true)) {
                    this.DatumDogodkaField = value;
                    this.RaisePropertyChanged("DatumDogodka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDogodka {
            get {
                return this.IdDogodkaField;
            }
            set {
                if ((this.IdDogodkaField.Equals(value) != true)) {
                    this.IdDogodkaField = value;
                    this.RaisePropertyChanged("IdDogodka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.AquaPark.KomentarDogodka[] KomentarDogodka {
            get {
                return this.KomentarDogodkaField;
            }
            set {
                if ((object.ReferenceEquals(this.KomentarDogodkaField, value) != true)) {
                    this.KomentarDogodkaField = value;
                    this.RaisePropertyChanged("KomentarDogodka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.AquaPark.LokacijaDogodka Lokacija {
            get {
                return this.LokacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.LokacijaField, value) != true)) {
                    this.LokacijaField = value;
                    this.RaisePropertyChanged("Lokacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxSteviloPrijav {
            get {
                return this.MaxSteviloPrijavField;
            }
            set {
                if ((this.MaxSteviloPrijavField.Equals(value) != true)) {
                    this.MaxSteviloPrijavField = value;
                    this.RaisePropertyChanged("MaxSteviloPrijav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivDogodka {
            get {
                return this.NazivDogodkaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivDogodkaField, value) != true)) {
                    this.NazivDogodkaField = value;
                    this.RaisePropertyChanged("NazivDogodka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PovprecnaOcena {
            get {
                return this.PovprecnaOcenaField;
            }
            set {
                if ((this.PovprecnaOcenaField.Equals(value) != true)) {
                    this.PovprecnaOcenaField = value;
                    this.RaisePropertyChanged("PovprecnaOcena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.AquaPark.TipDogodka TipDogodka {
            get {
                return this.TipDogodkaField;
            }
            set {
                if ((this.TipDogodkaField.Equals(value) != true)) {
                    this.TipDogodkaField = value;
                    this.RaisePropertyChanged("TipDogodka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LokacijaDogodka", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    public partial class LokacijaDogodka : ApartmentComplexServiceLibraryV1.AquaPark.Lokacija {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivParkaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivParka {
            get {
                return this.NazivParkaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivParkaField, value) != true)) {
                    this.NazivParkaField = value;
                    this.RaisePropertyChanged("NazivParka");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KomentarDogodka", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    public partial class KomentarDogodka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OcenaDogodkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VsebinaKomentarjaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OcenaDogodka {
            get {
                return this.OcenaDogodkaField;
            }
            set {
                if ((this.OcenaDogodkaField.Equals(value) != true)) {
                    this.OcenaDogodkaField = value;
                    this.RaisePropertyChanged("OcenaDogodka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VsebinaKomentarja {
            get {
                return this.VsebinaKomentarjaField;
            }
            set {
                if ((object.ReferenceEquals(this.VsebinaKomentarjaField, value) != true)) {
                    this.VsebinaKomentarjaField = value;
                    this.RaisePropertyChanged("VsebinaKomentarja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipDogodka", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    public enum TipDogodka : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kanjoning = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rafting = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sportno_plezanje = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gorsko_kolesarjenje = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zorbing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zip_line = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bungee_jump = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bob_cart = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gokart = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paintball = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Airsoft = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lokacija", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.Narocnik))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.LokacijaDogodka))]
    public partial class Lokacija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesto {
            get {
                return this.MestoField;
            }
            set {
                if ((object.ReferenceEquals(this.MestoField, value) != true)) {
                    this.MestoField = value;
                    this.RaisePropertyChanged("Mesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posta {
            get {
                return this.PostaField;
            }
            set {
                if ((object.ReferenceEquals(this.PostaField, value) != true)) {
                    this.PostaField = value;
                    this.RaisePropertyChanged("Posta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Narocnik", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    public partial class Narocnik : ApartmentComplexServiceLibraryV1.AquaPark.Lokacija {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GesloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonskaStevilkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UporabniskoImeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geslo {
            get {
                return this.GesloField;
            }
            set {
                if ((object.ReferenceEquals(this.GesloField, value) != true)) {
                    this.GesloField = value;
                    this.RaisePropertyChanged("Geslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonskaStevilka {
            get {
                return this.TelefonskaStevilkaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonskaStevilkaField, value) != true)) {
                    this.TelefonskaStevilkaField = value;
                    this.RaisePropertyChanged("TelefonskaStevilka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UporabniskoIme {
            get {
                return this.UporabniskoImeField;
            }
            set {
                if ((object.ReferenceEquals(this.UporabniskoImeField, value) != true)) {
                    this.UporabniskoImeField = value;
                    this.RaisePropertyChanged("UporabniskoIme");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    public partial class FaultType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prijava", Namespace="http://www.adrenalinski-park.com/16/12/2014")]
    [System.SerializableAttribute()]
    public partial class Prijava : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumPrijaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.AquaPark.Dogodek DogodekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPrijavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LastenPrevozField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentComplexServiceLibraryV1.AquaPark.Narocnik NarocnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrijavaPlacanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SteviloOsebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumPrijave {
            get {
                return this.DatumPrijaveField;
            }
            set {
                if ((this.DatumPrijaveField.Equals(value) != true)) {
                    this.DatumPrijaveField = value;
                    this.RaisePropertyChanged("DatumPrijave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.AquaPark.Dogodek Dogodek {
            get {
                return this.DogodekField;
            }
            set {
                if ((object.ReferenceEquals(this.DogodekField, value) != true)) {
                    this.DogodekField = value;
                    this.RaisePropertyChanged("Dogodek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrijava {
            get {
                return this.IdPrijavaField;
            }
            set {
                if ((this.IdPrijavaField.Equals(value) != true)) {
                    this.IdPrijavaField = value;
                    this.RaisePropertyChanged("IdPrijava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LastenPrevoz {
            get {
                return this.LastenPrevozField;
            }
            set {
                if ((this.LastenPrevozField.Equals(value) != true)) {
                    this.LastenPrevozField = value;
                    this.RaisePropertyChanged("LastenPrevoz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentComplexServiceLibraryV1.AquaPark.Narocnik Narocnik {
            get {
                return this.NarocnikField;
            }
            set {
                if ((object.ReferenceEquals(this.NarocnikField, value) != true)) {
                    this.NarocnikField = value;
                    this.RaisePropertyChanged("Narocnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrijavaPlacana {
            get {
                return this.PrijavaPlacanaField;
            }
            set {
                if ((this.PrijavaPlacanaField.Equals(value) != true)) {
                    this.PrijavaPlacanaField = value;
                    this.RaisePropertyChanged("PrijavaPlacana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SteviloOseb {
            get {
                return this.SteviloOsebField;
            }
            set {
                if ((this.SteviloOsebField.Equals(value) != true)) {
                    this.SteviloOsebField = value;
                    this.RaisePropertyChanged("SteviloOseb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.adrenalinski-park.com/16/12/2014", ConfigurationName="AquaPark.DogodkiService")]
    public interface DogodkiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodke", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeFaultTypeFa" +
            "ult", Name="FaultType")]
        ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniDogodke();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodke", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeResponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniDogodkeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniPrihajajoceDogodke" +
            "", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniPrihajajoceDogodke" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniPrihajajoceDogodke" +
            "FaultTypeFault", Name="FaultType")]
        ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniPrihajajoceDogodke();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniPrihajajoceDogodke" +
            "", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniPrihajajoceDogodke" +
            "Response")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniPrihajajoceDogodkeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeMedDatumoma" +
            "", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeMedDatumoma" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeMedDatumoma" +
            "FaultTypeFault", Name="FaultType")]
        ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniDogodkeMedDatumoma(System.DateTime datumOd, System.DateTime datumDo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeMedDatumoma" +
            "", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeMedDatumoma" +
            "Response")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniDogodkeMedDatumomaAsync(System.DateTime datumOd, System.DateTime datumDo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeGledeNaTip", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeGledeNaTipR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeGledeNaTipF" +
            "aultTypeFault", Name="FaultType")]
        ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniDogodkeGledeNaTip(ApartmentComplexServiceLibraryV1.AquaPark.TipDogodka tipDogodka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeGledeNaTip", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniDogodkeGledeNaTipR" +
            "esponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniDogodkeGledeNaTipAsync(ApartmentComplexServiceLibraryV1.AquaPark.TipDogodka tipDogodka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PridobiCenoDogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PridobiCenoDogodkaResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PridobiCenoDogodkaFaul" +
            "tTypeFault", Name="FaultType")]
        double PridobiCenoDogodka(int idDogodka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PridobiCenoDogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PridobiCenoDogodkaResp" +
            "onse")]
        System.Threading.Tasks.Task<double> PridobiCenoDogodkaAsync(int idDogodka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/IzracunCeneSkupinskePr" +
            "ijave", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/IzracunCeneSkupinskePr" +
            "ijaveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/IzracunCeneSkupinskePr" +
            "ijaveFaultTypeFault", Name="FaultType")]
        double IzracunCeneSkupinskePrijave(int idDogodka, int stPrijav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/IzracunCeneSkupinskePr" +
            "ijave", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/IzracunCeneSkupinskePr" +
            "ijaveResponse")]
        System.Threading.Tasks.Task<double> IzracunCeneSkupinskePrijaveAsync(int idDogodka, int stPrijav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniSteviloProstihMest" +
            "Dogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniSteviloProstihMest" +
            "DogodkaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniSteviloProstihMest" +
            "DogodkaFaultTypeFault", Name="FaultType")]
        int VrniSteviloProstihMestDogodka(int idDogodka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniSteviloProstihMest" +
            "Dogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/VrniSteviloProstihMest" +
            "DogodkaResponse")]
        System.Threading.Tasks.Task<int> VrniSteviloProstihMestDogodkaAsync(int idDogodka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaDogodek", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaDogodekRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaDogodekFaultT" +
            "ypeFault", Name="FaultType")]
        ApartmentComplexServiceLibraryV1.AquaPark.Prijava PrijavaNaDogodek(int idDogodka, string upIme, string geslo, int stOseb, bool lastniPrevoz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaDogodek", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaDogodekRespon" +
            "se")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Prijava> PrijavaNaDogodekAsync(int idDogodka, string upIme, string geslo, int stOseb, bool lastniPrevoz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OdjavaZdogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OdjavaZdogodkaResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OdjavaZdogodkaFaultTyp" +
            "eFault", Name="FaultType")]
        bool OdjavaZdogodka(int idPrijave, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OdjavaZdogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OdjavaZdogodkaResponse" +
            "")]
        System.Threading.Tasks.Task<bool> OdjavaZdogodkaAsync(int idPrijave, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PregledLastnihPrijav", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PregledLastnihPrijavRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PregledLastnihPrijavFa" +
            "ultTypeFault", Name="FaultType")]
        ApartmentComplexServiceLibraryV1.AquaPark.Prijava[] PregledLastnihPrijav(string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PregledLastnihPrijav", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PregledLastnihPrijavRe" +
            "sponse")]
        System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Prijava[]> PregledLastnihPrijavAsync(string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajKomentarDogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajKomentarDogodkaRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajKomentarDogodkaFa" +
            "ultTypeFault", Name="FaultType")]
        bool DodajKomentarDogodka(int idDogodka, string komentar, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajKomentarDogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajKomentarDogodkaRe" +
            "sponse")]
        System.Threading.Tasks.Task<bool> DodajKomentarDogodkaAsync(int idDogodka, string komentar, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajOcenoDogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajOcenoDogodkaRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajOcenoDogodkaFault" +
            "TypeFault", Name="FaultType")]
        bool DodajOcenoDogodka(int idDogodka, int ocena, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajOcenoDogodka", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/DodajOcenoDogodkaRespo" +
            "nse")]
        System.Threading.Tasks.Task<bool> DodajOcenoDogodkaAsync(int idDogodka, int ocena, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaObvestila", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaObvestilaResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaObvestilaFaul" +
            "tTypeFault", Name="FaultType")]
        bool PrijavaNaObvestila(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaObvestila", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PrijavaNaObvestilaResp" +
            "onse")]
        System.Threading.Tasks.Task<bool> PrijavaNaObvestilaAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OrganizirajPrevoz", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OrganizirajPrevozRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OrganizirajPrevozFault" +
            "TypeFault", Name="FaultType")]
        bool OrganizirajPrevoz(int idPrijave, string lokacijaPrevzema, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OrganizirajPrevoz", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/OrganizirajPrevozRespo" +
            "nse")]
        System.Threading.Tasks.Task<bool> OrganizirajPrevozAsync(int idPrijave, string lokacijaPrevzema, string uporabniskoIme, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PlacajPrijavo", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PlacajPrijavoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ApartmentComplexServiceLibraryV1.AquaPark.FaultType), Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PlacajPrijavoFaultType" +
            "Fault", Name="FaultType")]
        bool PlacajPrijavo(int idPrijave, string uporabniskoIme, string geslo, string TRR, bool placajPrekoERacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PlacajPrijavo", ReplyAction="http://www.adrenalinski-park.com/16/12/2014/DogodkiService/PlacajPrijavoResponse")]
        System.Threading.Tasks.Task<bool> PlacajPrijavoAsync(int idPrijave, string uporabniskoIme, string geslo, string TRR, bool placajPrekoERacuna);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DogodkiServiceChannel : ApartmentComplexServiceLibraryV1.AquaPark.DogodkiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DogodkiServiceClient : System.ServiceModel.ClientBase<ApartmentComplexServiceLibraryV1.AquaPark.DogodkiService>, ApartmentComplexServiceLibraryV1.AquaPark.DogodkiService {
        
        public DogodkiServiceClient() {
        }
        
        public DogodkiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DogodkiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DogodkiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DogodkiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniDogodke() {
            return base.Channel.VrniDogodke();
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniDogodkeAsync() {
            return base.Channel.VrniDogodkeAsync();
        }
        
        public ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniPrihajajoceDogodke() {
            return base.Channel.VrniPrihajajoceDogodke();
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniPrihajajoceDogodkeAsync() {
            return base.Channel.VrniPrihajajoceDogodkeAsync();
        }
        
        public ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniDogodkeMedDatumoma(System.DateTime datumOd, System.DateTime datumDo) {
            return base.Channel.VrniDogodkeMedDatumoma(datumOd, datumDo);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniDogodkeMedDatumomaAsync(System.DateTime datumOd, System.DateTime datumDo) {
            return base.Channel.VrniDogodkeMedDatumomaAsync(datumOd, datumDo);
        }
        
        public ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[] VrniDogodkeGledeNaTip(ApartmentComplexServiceLibraryV1.AquaPark.TipDogodka tipDogodka) {
            return base.Channel.VrniDogodkeGledeNaTip(tipDogodka);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Dogodek[]> VrniDogodkeGledeNaTipAsync(ApartmentComplexServiceLibraryV1.AquaPark.TipDogodka tipDogodka) {
            return base.Channel.VrniDogodkeGledeNaTipAsync(tipDogodka);
        }
        
        public double PridobiCenoDogodka(int idDogodka) {
            return base.Channel.PridobiCenoDogodka(idDogodka);
        }
        
        public System.Threading.Tasks.Task<double> PridobiCenoDogodkaAsync(int idDogodka) {
            return base.Channel.PridobiCenoDogodkaAsync(idDogodka);
        }
        
        public double IzracunCeneSkupinskePrijave(int idDogodka, int stPrijav) {
            return base.Channel.IzracunCeneSkupinskePrijave(idDogodka, stPrijav);
        }
        
        public System.Threading.Tasks.Task<double> IzracunCeneSkupinskePrijaveAsync(int idDogodka, int stPrijav) {
            return base.Channel.IzracunCeneSkupinskePrijaveAsync(idDogodka, stPrijav);
        }
        
        public int VrniSteviloProstihMestDogodka(int idDogodka) {
            return base.Channel.VrniSteviloProstihMestDogodka(idDogodka);
        }
        
        public System.Threading.Tasks.Task<int> VrniSteviloProstihMestDogodkaAsync(int idDogodka) {
            return base.Channel.VrniSteviloProstihMestDogodkaAsync(idDogodka);
        }
        
        public ApartmentComplexServiceLibraryV1.AquaPark.Prijava PrijavaNaDogodek(int idDogodka, string upIme, string geslo, int stOseb, bool lastniPrevoz) {
            return base.Channel.PrijavaNaDogodek(idDogodka, upIme, geslo, stOseb, lastniPrevoz);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Prijava> PrijavaNaDogodekAsync(int idDogodka, string upIme, string geslo, int stOseb, bool lastniPrevoz) {
            return base.Channel.PrijavaNaDogodekAsync(idDogodka, upIme, geslo, stOseb, lastniPrevoz);
        }
        
        public bool OdjavaZdogodka(int idPrijave, string uporabniskoIme, string geslo) {
            return base.Channel.OdjavaZdogodka(idPrijave, uporabniskoIme, geslo);
        }
        
        public System.Threading.Tasks.Task<bool> OdjavaZdogodkaAsync(int idPrijave, string uporabniskoIme, string geslo) {
            return base.Channel.OdjavaZdogodkaAsync(idPrijave, uporabniskoIme, geslo);
        }
        
        public ApartmentComplexServiceLibraryV1.AquaPark.Prijava[] PregledLastnihPrijav(string uporabniskoIme, string geslo) {
            return base.Channel.PregledLastnihPrijav(uporabniskoIme, geslo);
        }
        
        public System.Threading.Tasks.Task<ApartmentComplexServiceLibraryV1.AquaPark.Prijava[]> PregledLastnihPrijavAsync(string uporabniskoIme, string geslo) {
            return base.Channel.PregledLastnihPrijavAsync(uporabniskoIme, geslo);
        }
        
        public bool DodajKomentarDogodka(int idDogodka, string komentar, string uporabniskoIme, string geslo) {
            return base.Channel.DodajKomentarDogodka(idDogodka, komentar, uporabniskoIme, geslo);
        }
        
        public System.Threading.Tasks.Task<bool> DodajKomentarDogodkaAsync(int idDogodka, string komentar, string uporabniskoIme, string geslo) {
            return base.Channel.DodajKomentarDogodkaAsync(idDogodka, komentar, uporabniskoIme, geslo);
        }
        
        public bool DodajOcenoDogodka(int idDogodka, int ocena, string uporabniskoIme, string geslo) {
            return base.Channel.DodajOcenoDogodka(idDogodka, ocena, uporabniskoIme, geslo);
        }
        
        public System.Threading.Tasks.Task<bool> DodajOcenoDogodkaAsync(int idDogodka, int ocena, string uporabniskoIme, string geslo) {
            return base.Channel.DodajOcenoDogodkaAsync(idDogodka, ocena, uporabniskoIme, geslo);
        }
        
        public bool PrijavaNaObvestila(string email) {
            return base.Channel.PrijavaNaObvestila(email);
        }
        
        public System.Threading.Tasks.Task<bool> PrijavaNaObvestilaAsync(string email) {
            return base.Channel.PrijavaNaObvestilaAsync(email);
        }
        
        public bool OrganizirajPrevoz(int idPrijave, string lokacijaPrevzema, string uporabniskoIme, string geslo) {
            return base.Channel.OrganizirajPrevoz(idPrijave, lokacijaPrevzema, uporabniskoIme, geslo);
        }
        
        public System.Threading.Tasks.Task<bool> OrganizirajPrevozAsync(int idPrijave, string lokacijaPrevzema, string uporabniskoIme, string geslo) {
            return base.Channel.OrganizirajPrevozAsync(idPrijave, lokacijaPrevzema, uporabniskoIme, geslo);
        }
        
        public bool PlacajPrijavo(int idPrijave, string uporabniskoIme, string geslo, string TRR, bool placajPrekoERacuna) {
            return base.Channel.PlacajPrijavo(idPrijave, uporabniskoIme, geslo, TRR, placajPrekoERacuna);
        }
        
        public System.Threading.Tasks.Task<bool> PlacajPrijavoAsync(int idPrijave, string uporabniskoIme, string geslo, string TRR, bool placajPrekoERacuna) {
            return base.Channel.PlacajPrijavoAsync(idPrijave, uporabniskoIme, geslo, TRR, placajPrekoERacuna);
        }
    }
}
